server:
  address: 0.0.0.0
  port: 80

spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


  datasource:
    url: jdbc:mysql://localhost:3306/tsai_blog?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username:
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 2
    host: localhost
    port: 6379
    password: 123
    timeout: 500
    pool:
      max-active: 8
      min-idle: 0
      max-wait: 1
      max-idle: 8

mybatis:
  type-aliases-package: com.ilsxh.blog.entity
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

